const paletteData = "IRgbcmdrR0FrbIxQ49JF+KRet0hGTigumkB+qspT+fXvmZ7XkWxSIzkq3b6L";

loadPalette();

const guyData = "DAkIDwUCAAMFBxAAQABAAFAB8AvwCqAKkAZUhVEVQgXMD/A/ADAAwA0JBw8FAgADBQcFAARABfALvAKqABpQhVQFVUA/4A/AAwADwAANCAUQBQIAAwUHBERABb+8ogoKVFRRBRXc/MIDDAwNCAYQBQIAAwUHBQABVMAvvIIqoAAVVEEVVIn/8A8/MMAADQgGEAUCAAMFBwFAABBABfzCK6gCClRRFVVZFfID/8wzAA0IBRAMAgADBQcFQEAFv7yiCgpVVFFFFf7wwAMzzA0IBRAMAgADBQcBEAABFfzyiiooVFFFFVX4wwMzzA0KBQ4MAgADBQcFQEAFv7yiShpVVFGFPzwwwwwNCQUPDAIAAwUHBERABb+8okoaVVRRhT888MAMMwoHCg8KAgADBQcABQBUAQC/APAKAKoAlQJEVSBQFQAVBVCBAD0A9AMwDwD8AMAAAAsHCQ8KAgADBQdQAQAVAPwC8AqAKkApQFVBUBVCBQEVCPUA8APMA8APAAMACgULEQoCAAMFBwABAAABAEAAAFQAAL8AwCsAoApApQFEVYFAFQFQAQL0AwD/A8DDAPAwADAAAAwACwULEQoCAAMFBxAAABAAABAAABUAwC8A8AoAqAJAaQFUFUVQBShUAAD9AMD/APAwADwMAAwAAAMACwgQEBACAAMFB1AAAAAAAQAAQAUAAMIvAEDBKwAUgSpAAQQKoABQFQUAQFUAAEAVAABABQAAwA8AAMAwAADAwAAAMMAAAAzAAAALCBAQEAIAAwUHEAAAAEAAAAAAAQAAQgUAQMEvABTBK0ABhCqgAFAaBQBAVQAAQBUAAEAFAADADwAAwDAAAMDAAAAwwAAADMAAAAsJEA8QAgADBQdQAAAAAAEAAEAFAADCLwBAwSsAFIEqQAEECqAAUBoFAEBVAABAFQAAQAUAAMAwAADAwAAAwMAAADzAAAALCBAQDQIAAwUHUAAAAAABAABABQAAwi8AQMErABSBKkABBAqgAFAVBQBAVQAAQBUAAEAFAADADwAAwDAAAMDAAAAwwAAADMAAAAoHERENAgADBQcABAAAAEQAAABABQAAAL8AQAK8AlAEoAoUQIACKABUFQUAAFUBAABUAQAAUAEAAMAPAAAA/wAAAAwMAAAMwAAADAAMAAwAAAAACgcREQ0CAAMFB0AAAAAABAAAAEAAAABABQAACL8AABG8AkBBoApQAAQKoABAVRQAAFQFAABQBQAAQAUAAAA/AAAADAMAAAwwAAAPwAAAAwADAAAMChQOCgIAAwUHAEABAAAAVQUAAAD8LwAAAPArAAAKoCoAAFSACgAAUFVVVlUAVQUAAEBVAAAAAP8AAADA/wMAAPDADwAAPAAPAAAMAAwAAA0KEw4KAgADBQcAVAAAAABUAAAAAL8AAADAKwAAAqAKAAAFoAAAAFRVWVUBVAUAAAAVAAAAwA8AAAD8DwAAwAAMAAAMAAMAwADAAAAACQgLEA8CAAMFB0ABAFQBAPwCAK8AgCoAgAIAVVVRVYECFQRARQDwBwBMAwDDAMDAAAwwAAMwDAkIDwgCAAMFB1UAUAP0CrAKoAuAAlAFVBVERWAlwD/AMMDwwADwAAwICBAIAgADBQdUAFED9AqwCqALoAuAAlAFVBVERWAlwD/AMMDwwADwAAwICBAIAgADBQdVAFAD9AqwCqALgAJQBVQVREVgJcAPwD/AMMDwwADwAAwHCBEIAgADBQcBAFQAUAP0CrAKoAugC4ACUAVUFURFYCXAP8AwwPDAAPAACgkSEQoCAAMFBwAFAAAAAAEAAABUAAAAwC8AAAK8AgBAgSoAEEClAQAAQFUAVABUBQAAQFUJVQD8aEEFMDBVAQADXFUBDMBVVTAAU1UBAABVAQAAUAAACggJEBQCAAMFBwABABEAUAHALwKvBKhCgAJUFQBVAVQFUBXAjwBDAUMNTDFMwQkGEhIUAgADBQcAAAABAAAAUAAAAEAVAAEAVAFAAFBVABAAVRVABVRVAPyCVgDAK5VABahWQFVQWgAAQFABAFQCFQAABVABAADA/wNAAAMwAAAwAAwAwADAAAALBQkTHgIAAwUHAAABAAQAEAVAQABBBQS/ILxCoAoBCgFVAVEBRAUEFSD8ADAMMMDAAAwDMA==";

const guyTags = {
  run: [0, 4] as AnimRange,
  idle: [5, 8] as AnimRange,
  jump: [9, 10] as AnimRange,
  fall: [11, 12] as AnimRange,
  garde: [13, 15] as AnimRange,
  advance: [16, 18] as AnimRange,
  lunge: [19, 20] as AnimRange,
  draw: [21, 21] as AnimRange,
  victory: [22, 25] as AnimRange,
  feint: [26, 27] as AnimRange,
  parry: [28, 29] as AnimRange,
}

const guyAnim = makeAnim(guyData);

const fontData = "AAABBgoBBS8AAAQDCgEFqgUAAAYGCgEFDMO0HgMAAAUFCgEG6n9HAAAABQUKAQeqRkUAAAAEBgoBBVKltQAAAgIKAQUGAAADBgoBBVQiAgAAAwYKAQURqQAAAAQGCgEF////AAIDAwoBBboAAAQCAgoBBQYAAwMBCgEFBwAFAQEKAQUBAAADBgoBBaSUAAAAAwYKAQVqWwEAAAMGCgEFk6QDAAADBgoBBaOTAwAAAwYKAQWjyAEAAAMGCgEFrUkCAAADBgoBBc/IAQAAAwYKAQXOWgEAAAMGCgEFJ0kCAAADBgoBBapaAQAAAwYKAQWqyQEAAQEECgEFCQABAQUKAQUZAAAFBgoBBUT8LwgAAQMDCgEFxwEAAAUGCgEFBP2PCAAAAwYKAQUvBQEAAAQGCgEFn93xAAAEBgoBBZf5mQAABAYKAQWXefkAAAQGCgEFHhHhAAAEBgoBBZeZeQAABAYKAQUfF/EAAAQGCgEFHxcRAAAEBgoBBR6deQAABAYKAQWZn5kAAAMGCgEFl6QDAAADBgoBBSbZAwAABAYKAQWZNZUAAAQGCgEFERHxAAAFBgoBBXHXWisAAAUGCgEFcdaaIwAABQYKAQUuxhgdAAAEBgoBBZd5EQAABQYKAQUuxpgsAAAEBgoBBZd5mQAABAYKAQUeYfgAAAUGCgEFnxBCCAAABAYKAQWZmWkAAAUGCgEFMSpFCAAABQYKAQUxxlodAAAFBgoBBVERoiIAAAUGCgEFMUZHCAAABAYKAQXPJPMAAAMGCgEFT5IDAAADBgoBBYlEAgAAAwYKAQUnyQMAAAYGCgEFjNcyDAM=";

const fontAnim = makeAnim(fontData);

const forestTilesData = "AAAICAoBCf/M//+dDQQEAAAIBwoBCf9s///95iYAAAgICgEJ/7T/7/l5ODACAAQIAAEM73///gAACAgAAQ7//3z/P348PAACCAYKAQ0gtf////8AAAgHCgEBPH7w7l8/fgAACAgKAQF27w9g/v//fgAACAgKAQE4fH7+/fvnXgAGCAIKAQFm9wAACAgKAQEpOekpLykpKQAACAgKAQFA4EBETkTk/wAACAgKAQ3//////////w==";

const forestTilesTags = {
  ground: [0, 2] as AnimRange,
  stump: [3, 3] as AnimRange,
  stumpCap: [4, 4] as AnimRange,
  grass: [5, 5] as AnimRange,
  stone: [6, 7] as AnimRange,
  stoneCap: [8, 8] as AnimRange,
  stoneTrim: [9, 9] as AnimRange,
  gate: [10, 10] as AnimRange,
  gateCap: [11, 12] as AnimRange,
  solidGrass: [12, 12] as AnimRange,
}

const forestTilesAnim = makeAnim(forestTilesData);

const dummyData = "CggKERkBBThQwQcXOEAIIW58TAADBCCAAAQYQAAJBw0SGQEF4AAqwAe4AA6AIDjDH0cACAADIAAEAAEwAASAABAACwgOERkBBeAAVAAVwAcwAUwADtzn+AcQAAwAAUAACAADgAAgAAkFDhRkAQUAB6ACqAA+gAvgA3AA4PcPfgAEgAEgAAQAAUAAIAAYAAgAAggICREPAQXgQMOHDHkyO3hAwEBGBAggYIAAAQcODQsPAQUAyDd9w0r4sTJCRnAQAANAAAgGEhAHDwEFDgC/gdVCn0QZNhkEDgQEERMIDwEFDgCoAEAFAD4YkQGJr4w4RhggAgISFgcPAQUOAMAHAPABAnwAARViwEeQ6SyEAQ==";

const dummyTags = {
  idle: [0, 2] as AnimRange,
  hit: [3, 3] as AnimRange,
  death: [4, 8] as AnimRange,
}

const dummyAnim = makeAnim(dummyData);

const targetData = "CQgNEAoBCOABQiATkkStlKlKVamVulKXabUuyck8woffCQkODwoBCEAA6ABBICcIEmVFnQr9WnW1rtlr8mQewge/AQ==";

const targetTags = {
  idle: [0, 0] as AnimRange,
  hit: [1, 1] as AnimRange,
}

const targetAnim = makeAnim(targetData);

const coinData = "DRAGCAoBBIwUtmkoMQ4QBAgKAQTW/b9rDxACCAoBBP//";

const coinTags = {
  idle: [0, 2] as AnimRange,
}

const coinAnim = makeAnim(coinData);

const portraitData = "AAAWGQoBBADgAIA/APgegJ8H4MEBEGAAdAuAkQBgAAEYwAD2N4D9D8DDA/B/APgPcP4b4jxZMEAIEAgg+CEAAAAAAAB3dQDVFTBXBQAAFhkKAQQA4ACAPwD4HoCfB+DBARBgAHQLgJEAYAABGMAA9jeADQ/AwwPweQD4D3D+G+I8WTBACBAIIPghAAAAAAAAd3UA1RUwVwUBAhMXCgEEwAYAXwAMBDBAgLgDICBASAEBCChAQAAChBEgjIADDv77+OEvL56QYwAIAEAAAADA1RWkYiB3BQECExcKAQTABgBfAAwEMECAuAMgIEBIAQEIKEBAAALEESCAgAMO/vv44S8vnpBjAAgAQAAAAMDVFaRiIHcFAQAUGQoBBIA/AP4P8P8BBxAwPwD4FxgA4gRoJ7N+I+o3gG4DaCSAxsJoSECDDRJYv8EMGr6/8wd+//8HAAB8d0V1cVQVAgEAFBkKAQSAPwD+D/D/AQcQMD8A+BcYAOIEaCezfiPqN4BuA2gkgMbCaEhMgw0SWKHB7Bu+v/MHfv//BwAAfHdFdXFUFQI=";

const portraitTags = {
  John: [0, 1] as AnimRange,
  Tuck: [2, 3] as AnimRange,
  Mary: [4, 5] as AnimRange,
}

const portraitAnim = makeAnim(portraitData);

const merryData = "DQcJEQoBCT74sMCDBwYefrZp4sODAwUJEmMADQYJEgoBCTz8sMCDBwYMPPxs08SHBwcKEiXEAA0GCRIKAQk++LDAgwcGHn62aeLDAwMHChIkxgANBQkTCgEJAnjwYYEHDww8/GzTxIcHBg4UJEiMAQgHEREOAQl8APABYAGABwAPAAwgPCB8IPQgxiaAMYAEABEAIgCEAAgBGAYACQcREQ4BCQQA8ADgA8ACAA8AHiAYIHwg9CDGJoAxgAQAEQAhAEIAhAAMAwAKBxERDgEJeAD4AWABgAcADwAMIDwgfCD0IMYmgDGABIAIABEAIQBCAIYBAAoHERESAQkEAPAA4APAAgAPAB4gGCB8IPQgxiaAMQADwAeABAAEAAgAMAAACQYREhIBCXgA+AFgAYAHAA8ADCA8IHwg9CDGJoAxAA8AHgAUABgACAAIADAAAAgHEhESAQn4AMAHAAsAeADgAQADCB4QfiDnQQCbAIwBMABAAQAJAEMAAgEYDAACBxERGQEJgA+ADwAaAB4AOADgAOADYAewB9AP8P/x/9D/3wAI/BcAIMDAAAQHDhEyAQnAA/gBNIAH4AEwAD5AFogDYUAwCAwCTzAUAyFAGDAFBA4UKAEJgABAABCAC3AFdIGGBCGBifDBPwAPgAHAADAAFAAJMAQCgcECBhESEgEJABAAIACAAA4BLwJ0BDAQQCAAIwA//B8APADwAMACAAmAIYBAAAMDCAUQExIBCQCAAIAAQMBB8ENgQcAjgCOAEfAPzAPDA4ABgAOABUAEMAIIAhgGCAULEx4BCQIgAA/8wAJ84AVGfNR33mIQAyhAAiIQgRCGAQkIFhAUAQkQAAB4AAA+AIAFAMADAPAAAAwA4H8A5vF/eAAADADABwAIAQAiAEAIABgGAAgHEBEPAQkCADwAfAAsAHgAeAAwAPwA+gB5ATECOQxIMEjAiACIAIwBBwUREw8BCQAQAGAAwBGAwwOPDx4LPjz8eHxh/OJ/5f9KRlUMajxQRIAIASACYAwABgQOFCgBCQAgAAgAAoB8ID6IBcFD8AgYAT/gA8TAMAAeQAQQAYQAIsAYCgcQERQBCR8APgAWADwAHAAYBjwB/gA+AF4AHAAkwEQwSAyIAIQAhgEJChIOMgEJ+AHAAgA/AHgB4AkAIwBeAPwA8AHADwA/AEwAMwF07Q8HFBUEGQEJAOADwPs8//+49g8=";

const merryTags = {
  idle: [0, 3] as AnimRange,
  garde: [4, 6] as AnimRange,
  advance: [7, 9] as AnimRange,
  flinch: [10, 11] as AnimRange,
  hit: [12, 14] as AnimRange,
  windup: [15, 15] as AnimRange,
  lunge: [16, 17] as AnimRange,
  parry: [18, 19] as AnimRange,
  death: [20, 22] as AnimRange,
}

const merryAnim = makeAnim(merryData);

const piggyData = "BQ0VCwoBCAAEAYAxwNeF/f/BPz/4VyX/quS/f/z3g2sGoIgABQwVDAoBCAAEAYAxANAF+P6BPz/+VyX/quS/f/z3g/8GsNkAIQoABQwVDBQBCAAEAYAxANAF+P6xPz/4VyX/quS/f/z3g/8GsFkAEgoABQ0VCxQBCAAEAYAxwNeF/P7hPz/4VyX/quS/f/z3g40CkEAABQUUExQBCAAgAAACACAAAAAAIAAAAAAEAcAYAPwBwD/wo4K/qv+ryn9//P/DfwH8FcBGACQEAAULFA0UAQgABAHAGAD8AcA/8OOTv6r+q8p/f/z/w38B/BXARgAkBAA=";

const piggyTags = {
  run: [0, 1] as AnimRange,
  idle: [2, 3] as AnimRange,
  sniff: [4, 5] as AnimRange,
}

const piggyAnim = makeAnim(piggyData);

const spikeData = "CBcQAQoBDv//CBAQCAoBDhAQODi4OJAQUBR8fHg4//8IChAOCgEOEBA4OFRUEBAQERERERGSEJISlJKUVFhUWDn//w==";

const spikeTags = {
  pop: [0, 2] as AnimRange,
}

const spikeAnim = makeAnim(spikeData);

const flamesData = "DRIIBgoBBgQEDJ7//w0QCAgKAQYIDAwMiMIe/w4QBwgKAQYEBgYKEhgeDRAICAoBBhAwoAAEDBx/DRAHCAoBBigAgEBw+P4=";

const flamesTags = {
  burning: [0, 4] as AnimRange,
}

const flamesAnim = makeAnim(flamesData);